/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Wed Apr 20 15:42:46 2016. */

#include "boat.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const shedBoat_Telemetry_Status shedBoat_Telemetry_status_default = shedBoat_Telemetry_Status_UNDEFINED;


const pb_field_t shedBoat_Telemetry_fields[6] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, shedBoat_Telemetry, status, status, &shedBoat_Telemetry_status_default),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, shedBoat_Telemetry, location, status, &shedBoat_Location_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, STATIC  , OTHER, shedBoat_Telemetry, motor, location, &shedBoat_Motor_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, shedBoat_Telemetry, battery, motor, &shedBoat_Battery_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, shedBoat_Telemetry, debug, battery, &shedBoat_Debug_fields),
    PB_LAST_FIELD
};

const pb_field_t shedBoat_Location_fields[9] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, shedBoat_Location, latitude, latitude, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, shedBoat_Location, longitude, latitude, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, shedBoat_Location, number_of_satellites_visible, longitude, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, shedBoat_Location, speed_over_ground, number_of_satellites_visible, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, shedBoat_Location, true_heading, speed_over_ground, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, shedBoat_Location, true_bearing, true_heading, 0),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, shedBoat_Location, utc_seconds, true_bearing, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, shedBoat_Location, fix_quality, utc_seconds, 0),
    PB_LAST_FIELD
};

const pb_field_t shedBoat_Motor_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, shedBoat_Motor, motor_number, motor_number, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, shedBoat_Motor, is_alive, motor_number, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, shedBoat_Motor, rpm, is_alive, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, shedBoat_Motor, temperature, rpm, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, shedBoat_Motor, voltage, temperature, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, shedBoat_Motor, current, voltage, 0),
    PB_LAST_FIELD
};

const pb_field_t shedBoat_Battery_fields[3] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, shedBoat_Battery, percent_full, percent_full, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, shedBoat_Battery, cell, percent_full, &shedBoat_Battery_Cell_fields),
    PB_LAST_FIELD
};

const pb_field_t shedBoat_Battery_Cell_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, shedBoat_Battery_Cell, cell_number, cell_number, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, shedBoat_Battery_Cell, voltage, cell_number, 0),
    PB_LAST_FIELD
};

const pb_field_t shedBoat_Debug_fields[5] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, shedBoat_Debug, bearing_compensation, bearing_compensation, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, shedBoat_Debug, speed_over_ground_compensation, bearing_compensation, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, shedBoat_Debug, motor_1_throttle_compensation, speed_over_ground_compensation, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, shedBoat_Debug, motor_2_throttle_compensation, motor_1_throttle_compensation, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(shedBoat_Telemetry, location) < 65536 && pb_membersize(shedBoat_Telemetry, motor[0]) < 65536 && pb_membersize(shedBoat_Telemetry, battery) < 65536 && pb_membersize(shedBoat_Telemetry, debug) < 65536 && pb_membersize(shedBoat_Battery, cell[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_shedBoat_Telemetry_shedBoat_Location_shedBoat_Motor_shedBoat_Battery_shedBoat_Battery_Cell_shedBoat_Debug)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(shedBoat_Telemetry, location) < 256 && pb_membersize(shedBoat_Telemetry, motor[0]) < 256 && pb_membersize(shedBoat_Telemetry, battery) < 256 && pb_membersize(shedBoat_Telemetry, debug) < 256 && pb_membersize(shedBoat_Battery, cell[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_shedBoat_Telemetry_shedBoat_Location_shedBoat_Motor_shedBoat_Battery_shedBoat_Battery_Cell_shedBoat_Debug)
#endif


/* @@protoc_insertion_point(eof) */
