/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.5 at Wed Apr 20 15:25:12 2016. */

#ifndef PB_BOAT_PB_H_INCLUDED
#define PB_BOAT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _shedBoat_Telemetry_Status {
    shedBoat_Telemetry_Status_UNDEFINED = 0,
    shedBoat_Telemetry_Status_UNDERWAY_MANUAL = 1,
    shedBoat_Telemetry_Status_UNDERWAY_AUTOPILOT = 2,
    shedBoat_Telemetry_Status_STATIONARY = 3,
    shedBoat_Telemetry_Status_RESTRICTED_MANEUVERABILITY = 4
} shedBoat_Telemetry_Status;

/* Struct definitions */
typedef struct _shedBoat_Battery {
    bool has_percent_full;
    int32_t percent_full;
    pb_callback_t cell;
/* @@protoc_insertion_point(struct:shedBoat_Battery) */
} shedBoat_Battery;

typedef struct _shedBoat_Battery_Cell {
    int32_t cell_number;
    bool has_voltage;
    int32_t voltage;
/* @@protoc_insertion_point(struct:shedBoat_Battery_Cell) */
} shedBoat_Battery_Cell;

typedef struct _shedBoat_Debug {
    bool has_bearing_compensation;
    int32_t bearing_compensation;
    bool has_speed_over_ground_compensation;
    int32_t speed_over_ground_compensation;
    bool has_motor_1_throttle_compensation;
    int32_t motor_1_throttle_compensation;
    bool has_motor_2_throttle_compensation;
    int32_t motor_2_throttle_compensation;
/* @@protoc_insertion_point(struct:shedBoat_Debug) */
} shedBoat_Debug;

typedef struct _shedBoat_Location {
    bool has_latitude;
    float latitude;
    bool has_longitude;
    float longitude;
    bool has_number_of_satellites_visible;
    int32_t number_of_satellites_visible;
    bool has_speed_over_ground;
    int32_t speed_over_ground;
    bool has_true_heading;
    int32_t true_heading;
    bool has_true_bearing;
    int32_t true_bearing;
    bool has_utc_seconds;
    int32_t utc_seconds;
    bool has_fix_quality;
    float fix_quality;
/* @@protoc_insertion_point(struct:shedBoat_Location) */
} shedBoat_Location;

typedef struct _shedBoat_Motor {
    int32_t motor_number;
    bool has_is_alive;
    bool is_alive;
    bool has_rpm;
    int32_t rpm;
    bool has_temperature;
    int32_t temperature;
    bool has_voltage;
    int32_t voltage;
    bool has_current;
    int32_t current;
/* @@protoc_insertion_point(struct:shedBoat_Motor) */
} shedBoat_Motor;

typedef struct _shedBoat_Telemetry {
    shedBoat_Telemetry_Status status;
    bool has_location;
    shedBoat_Location location;
    pb_callback_t motor;
    bool has_battery;
    shedBoat_Battery battery;
    bool has_debug;
    shedBoat_Debug debug;
/* @@protoc_insertion_point(struct:shedBoat_Telemetry) */
} shedBoat_Telemetry;

/* Default values for struct fields */
extern const shedBoat_Telemetry_Status shedBoat_Telemetry_status_default;

/* Initializer values for message structs */
#define shedBoat_Telemetry_init_default          {shedBoat_Telemetry_Status_UNDEFINED, false, shedBoat_Location_init_default, {{NULL}, NULL}, false, shedBoat_Battery_init_default, false, shedBoat_Debug_init_default}
#define shedBoat_Location_init_default           {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define shedBoat_Motor_init_default              {0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define shedBoat_Battery_init_default            {false, 0, {{NULL}, NULL}}
#define shedBoat_Battery_Cell_init_default       {0, false, 0}
#define shedBoat_Debug_init_default              {false, 0, false, 0, false, 0, false, 0}
#define shedBoat_Telemetry_init_zero             {(shedBoat_Telemetry_Status)0, false, shedBoat_Location_init_zero, {{NULL}, NULL}, false, shedBoat_Battery_init_zero, false, shedBoat_Debug_init_zero}
#define shedBoat_Location_init_zero              {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define shedBoat_Motor_init_zero                 {0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define shedBoat_Battery_init_zero               {false, 0, {{NULL}, NULL}}
#define shedBoat_Battery_Cell_init_zero          {0, false, 0}
#define shedBoat_Debug_init_zero                 {false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define shedBoat_Battery_percent_full_tag        1
#define shedBoat_Battery_cell_tag                2
#define shedBoat_Battery_Cell_cell_number_tag    1
#define shedBoat_Battery_Cell_voltage_tag        2
#define shedBoat_Debug_bearing_compensation_tag  1
#define shedBoat_Debug_speed_over_ground_compensation_tag 2
#define shedBoat_Debug_motor_1_throttle_compensation_tag 3
#define shedBoat_Debug_motor_2_throttle_compensation_tag 4
#define shedBoat_Location_latitude_tag           1
#define shedBoat_Location_longitude_tag          2
#define shedBoat_Location_number_of_satellites_visible_tag 3
#define shedBoat_Location_speed_over_ground_tag  4
#define shedBoat_Location_true_heading_tag       5
#define shedBoat_Location_true_bearing_tag       6
#define shedBoat_Location_utc_seconds_tag        7
#define shedBoat_Location_fix_quality_tag        8
#define shedBoat_Motor_motor_number_tag          1
#define shedBoat_Motor_is_alive_tag              2
#define shedBoat_Motor_rpm_tag                   3
#define shedBoat_Motor_temperature_tag           4
#define shedBoat_Motor_voltage_tag               5
#define shedBoat_Motor_current_tag               6
#define shedBoat_Telemetry_status_tag            1
#define shedBoat_Telemetry_location_tag          2
#define shedBoat_Telemetry_motor_tag             3
#define shedBoat_Telemetry_battery_tag           4
#define shedBoat_Telemetry_debug_tag             5

/* Struct field encoding specification for nanopb */
extern const pb_field_t shedBoat_Telemetry_fields[6];
extern const pb_field_t shedBoat_Location_fields[9];
extern const pb_field_t shedBoat_Motor_fields[7];
extern const pb_field_t shedBoat_Battery_fields[3];
extern const pb_field_t shedBoat_Battery_Cell_fields[3];
extern const pb_field_t shedBoat_Debug_fields[5];

/* Maximum encoded size of messages (where known) */
#define shedBoat_Location_size                   70
#define shedBoat_Motor_size                      57
#define shedBoat_Battery_Cell_size               22
#define shedBoat_Debug_size                      44

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BOAT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
